### ISSUE TITLE
Loading classifier segmentation is never finished

### ISSUE THREAD

**Issue by fajri91** [arne-cl/feng-hirst-rst-parser#1]
Here is the output I get when I run `python parse.py -t test ../texts/wsj_0607.out`

> Added classifier classifier1 to segmenter gCRF
> Added feature writer to treebuilder
> Added classifier bin1 to treebuilder gCRF
> Added classifier mc1 to treebuilder gCRF
> Added classifier bin2 to treebuilder gCRF
> Added classifier mc2 to treebuilder gCRF
> Finished initialization in 0.89 seconds.
> 
> Processing 1 documents, skipping 0
> Parsing ../texts/wsj_0607.out, progress: 0.00 (0 out of 1)
> Processing sentence 0 out of 8
> Finished preprocessing in 1.69 seconds

It keeps running for hours. And when I run the sanity check, the output:

>  ********** Step 1: Now checking sentence splitting module...
> Successfully split the test file into 4 paragraphs and 8 sentences.
> 
> ********** Step 2: Now checking syntactic parsing module...
> Successfully unloaded syntax parser
> 
> ********** Step 3: Now checking CRFSuite classification module...
> *** Loading classifier segmentation...

It seems to me the code get stuck in performing `seq_prob, predictions = self.classifier.classify(features)` in `crf_segmenter.py`

Any idea?
Thanks

**Comment by arne-cl** [comment]
Dear Fajri,

I have never used the parser myself, so you would need to contact the original author (Vanessa Wei Feng) for help. 

If you don't need this specific RST parser, have a look at https://github.com/arne-cl/rst-workbench. You should be able to get the DPLP, CODRA and Heilman/Sagae RST parsers running.

Best,
Arne

**Comment by arne-cl** [comment]
Dear @fajri91,

I have no idea how the original code could have ever worked, but I was able to add a workaround.
I also added a Dockerfile and some unit tests to make working with the parser easier.

**Comment by fajri91** [comment]
Hi @arne-cl Thank you very much!
