### ISSUE TITLE
crfsuite-stdin: command not found

### ISSUE THREAD

**Issue by MousaMohammed** [arne-cl/feng-hirst-rst-parser#5]
Hi
after I finished all SETUP CRFSUITE steps
when I run this command " crfsuite-stdin tag -pi -m ../../model/tree_build_set_CRF/label/intra.crfsuite test.txt"
it gaves me this error "crfsuite-stdin: command not found"

**Comment by arne-cl** [comment]
Dear @MousaMohammed,
can you please try to install the parser using Docker, as described in my README?

Installing it locally on your machine is possible, but much more difficult.
That's why I made this repo in the first place.
